device: "auto"  # auto or 'cuda', 'cpu', 'mps' (for mac)

perception:
  lane_detection:
    model_path: "weights/tusimple_r18.onnx"
    # inference:
    conf_threshold: 0.4        # How confident the model must be to keep a detection
    nms_threshold: 50          # Threshold for non-maximum suppression
    max_lanes: 5               # Max number of lanes to return
    # image:
    input_width: 800           # Model input width
    input_height: 320          # Model input height
    original_width: 1280       # Original image width (from your camera or dataset)
    original_height: 720       # Original image height
    cut_height: 160            # How many pixels to cut from the bottom (for inference)

  object_detection:
    model_type: "PointRCNN"
    checkpoint: "weights/point_rcnn.pth"


decision:
  path_planning:
    max_speed: 3.0  # m/s
    min_distance: 2.0  # meters
    max_acceleration: 1.5  # m/s^2
    max_deceleration: 3.0  # m/s^2
